### PR TITLE
1.1.1: Making geoip2.reader service work with Symfony 4.2

### PR DESCRIPTION
**Pull request by classaxe**
I tried this earlier but one of the Travis tests - specifically 54.6 - timed out and failed.
Fingers crossed this time :-)

### CODE REVIEW

**Comment by classaxe** [comment]
Hi, I see that test 54.6 has errored out again.

Since all the other tests with PHP5.4 and Symfony passed, do you suppose this test itself might be faulty?

Anyway, I leave it with you.  The fix was to allow your tool to work properly with Symfony 4.2 without deprecation warnings.  I hope you like it, have a great weekend.

**Comment by peter-gribanov** [comment]
Thanks for the work you've done 👍

**Comment by peter-gribanov** [comment]
*If you need, you can close and reopen PR for rerun build Travis CI ([?](https://github.com/travis-ci/travis-ci/issues/576#issuecomment-65317915))*

**Comment by classaxe** [comment]
Thanks for producing this plugin, it is serving well in my project.
(https://github.com/classaxe/rxx_symfony)

Blessings,

Martin Francis
<><

**Pull request merged**
