### PR TITLE
Allow Symfony 7

### PR DESCRIPTION
**Pull request by Lustmored**
This is a simple PR allowing Symfony 7 components to be used with this bundle.

### CODE REVIEW

**Review by peter-gribanov — APPROVED** [review]

**Comment by peter-gribanov** [comment]
Tests fail. Please see what the problem might be.

**Comment by Lustmored** [comment]
> Tests fail. Please see what the problem might be.

Tests are failing on code coverage upload. I'm afraid it might be out of my reach to fix that, possibly something on the other side? It fails only for one case where I've changed PHP and Sf version to supported one (Sf 6.0->6.4 and PHP 8.0->8.1 per Sf requirements and new PHP 8.2 + Sf 7).

But I'll fix the CS for sure (errors are out of my changes, but that's trivial to fix anyways, so no problem).

**Comment by Lustmored** [comment]
@peter-gribanov I think I have fixed both code style and CI workflow so that it can pass, but the checks needs approval to be sure :+1:

**Comment by Lustmored** [comment]
I have ran them elsewhere only to find phpstan having some troubles. Sorry for the noise, I will investigate further...

**Comment by Lustmored** [comment]
@peter-gribanov I think I have won with phpstan. I cannot test code coverage upload, so please accept actions to see. I had to bump both phpstan and PHP minimal version (the latter is required by phpstan) and adapt to changes within.

How do you feel about dropping support for unmaintained PHP and/or Symfony versions? I can step up and create a PR with such work if that sounds good to you (or maybe even go for it in this one?)

**Review by peter-gribanov — APPROVED** [review]

**Comment by peter-gribanov** [comment]
Good job. Thank you

**Comment by peter-gribanov** [comment]
I made a new release [Releases 2.1.0](https://github.com/gpslab/geoip2/releases/tag/v2.1.0)

**Pull request merged**
